### ISSUE TITLE
Proposal to clarify meta and enhancement tags

### ISSUE THREAD

**Issue by JohnTurkson** [Wundero/Unofficial-210-TA-Guidelines#9]
I think the meta tag should relate to issues about the repository itself, such as:
- whether the repository is public
- who can make changes/merge PRs
- who can open issues and modify Project boards etc.

where as the enhancement tag should apply to guide contents, such as the proposal to create a new header/section in a specific file.

**Comment by Wundero** [comment]
I view enhancement as "upgrade" -> perhaps its not really necessary in the first place, as "documentation" should cover the use case anyways.

**Comment by JohnTurkson** [comment]
I was viewing "documentation" as "additions" to a given section, whereas "enhancements" as new sections outright.

**Comment by JohnTurkson** [comment]
Should we make a sticky somewhere (contributing.md maybe?) about Issue tags, and close this issue?

**Comment by Wundero** [comment]
why make a distinction?

**Comment by JohnTurkson** [comment]
I think there is room for ambiguity in the existing definitions. A sticky might clear things up/set the precedent for tag usage.

**Comment by Wundero** [comment]
i think enhancement only makes sense in a code situation, not pure docs

**Comment by JohnTurkson** [comment]
Do you then think enhancement and documentation should be merged? Or enhancement removed?

**Comment by Wundero** [comment]
merger but really just leave documentation

i can update the description to say "Modifications, deletions or additions to the documentation" if that makes more sense as a definition

**Comment by Wundero** [comment]
I am gonna update the description and close this issue. I believe the definitions should be rigorous enough after this.
